# Generated by Django 6.0.2 on 2026-03-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Books', 'Books'), ('Furniture', 'Furniture'), ('Sports', 'Sports'), ('Clothing', 'Clothing')], max_length=20)),
                ('condition', models.CharField(choices=[('Like New', 'Like New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], default='Good', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketplace_images/')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Pending', 'Pending')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
